# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more: 
# https://aka.ms/yaml

resources:
  repositories:
  - repository: "lkillgore/multirepopublic"
    type: github
    endpoint: "lkillgore"
    name: lkillgore/multirepomultirepopublic
    
trigger:
- master

pool: 'Default'
  
steps:
- checkout: self
- checkout: lkillgore/multirepopublic

- script: dir $(Build.SourcesDirectory)
